### PR TITLE
fix show_stats rebuild_index = True cause to clean index issue

### PR DESCRIPTION
**Pull request by zhangchunlin**
to fix the issue #21

### CODE REVIEW

**Comment by cbess** [comment]
I'm not sure what this really fixes. As the docs for `get_indexer()` says, rebuild_index is False by default.

**Comment by zhangchunlin** [comment]
You should notice that what I ran was "python main.py --index rebuild"
"rebuild" will cause the rebuild_index always True

**Comment by cbess** [comment]
I don't think it matters, because `show_stats` is what you updated. Which means you updated it to explicitly use its default value, which I think is not needed. Are you saying that "show_stats" is called when you rebuild the index?

**Comment by zhangchunlin** [comment]
Yes, I add a lot of log and found that.
my config file:
```
# settings overrides
# Make a copy of this file and rename it to `local_settings.yml`
# online yaml parser: http://yaml-online-parser.appspot.com/

# A value indicating whether the app runs in debug mode.
# type: boolean
# default: true (set to false for production or in untrusted environments)
debug: true

# The opposite of exclude_file_suffix. This **only** includes files that match a given suffix.
# type: tuple
# default: None
include_file_suffix: [
    '.m',
    '.c',
    '.cpp',
    '.m'
]

# The name of the server type to use as the web server.
# type: string
# default: '' or 'cherrypy'
server_type: 'cherrypy'

```

**Comment by cbess** [comment]
I'll look into it.

**Comment by cbess** [comment]
@zhangchunlin Is this still an issue?

**Comment by zhangchunlin** [comment]
@cbess Yes, it is still an issue.
I upgrade to your newest master, and got "Total documents indexed: 0"
So I don't know why you don't want to merge my pull request.
```
(sherlock_env)zhangclb@zhangclb2:~/sandbox/sherlock/opt/text-sherlock$ python main.py --index rebuild
Loaded Sherlock config settings from /home/zhangclb/sandbox/sherlock/opt/text-sherlock/local_settings.yml
Xapian backend support unavailable
Running sherlock...
Indexing path: /home/zhangclb/sandbox/sherlock/opt/text-sherlock/tests/text/
Reindexing everything!
Waiting 5s for interrupt...
Indexing started.
Available indexer backends: whoosh
Available searcher backends: whoosh
Current backend: whoosh
Total documents indexed: 0
Index Database: /home/zhangclb/sandbox/sherlock/opt/text-sherlock/data/indexes/main-index.db
Indexing done.

```

**Comment by cbess** [comment]
@zhangchunlin Merged. Thanks for the help

**Pull request merged**
